package pw.forst.wire.android.backups.database.model

import org.jetbrains.exposed.sql.Table

object Conversations : Table("Conversations") {
    val id = text("_id")
    val remoteId = text("remove_id")
    val name = text("name").nullable()
    val creator = text("creator")
    val conversationType = integer("conv_type")
    val team = text("team").nullable()
    val isManaged = integer("is_managed").nullable()
    val lastEventTime = integer("last_event_time")
    val isActive = integer("is_active")
    val lastRead = integer("last_read")
    val mutedStatus = integer("muted_status")
    val muteTime = integer("mute_time")
    val archived = integer("archived")
    val archiveTime = integer("archive_time")
    val cleared = integer("cleared").nullable()
    val generatedName = text("generated_name")
    val searchKey = text("search_key").nullable()
    val unreadCount = integer("unread_count")
    val unsentCount = integer("unsent_count")
    val hidden = integer("hidden")
    val missedCall = text("missed_call").nullable()
    val incomingKnock = text("incoming_knock").nullable()
    val verified = text("verified").nullable()
    val ephemeral = integer("ephemeral").nullable()
    val unreadCallCount = integer("unread_call_count")
    val unreadPingCount = integer("unread_ping_count")
    val access = text("access").nullable()
    val accessRole = text("access_role").nullable()
    val link = text("link").nullable()
    val unreadMentionsCount = integer("unread_mentions_count")
    val unreadQuoteCount = integer("unread_quote_count")
    val receiptMode = integer("receipt_mode").nullable()
    override val primaryKey = PrimaryKey(id)
}
